name: Build macOS wheels

on: [push, pull_request]

jobs:
  build_wheel:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-10.15]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install packages
        run: brew install coreutils

      - name: Build wheel
        run: sudo ./scripts/build-wheels-macOS.sh

      - uses: actions/upload-artifact@v2
        with:
          path: ./dist/mrob*.whl

  test_wheel:
    name: Test Python ${{ matrix.python }} wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: build_wheel
    strategy:
      fail-fast: false
      matrix:
        os: [macos-10.15]
        python: [3.5, 3.9]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Download artifacts
        uses: actions/download-artifact@v2

      - name: Install mrob & numpy
        run: |
          python3 -m pip install ./artifact/mrob*.whl numpy

      - name: Run FGraph_2d
        run: |
          python3 mrobpy/tests/FGraph_2d.py

      - name: Run FGraph_M3500
        run: |
          python3 mrobpy/tests/FGraph_M3500.py

      - name: Run FGraph_sphere
        run: |
          python3 mrobpy/tests/FGraph_sphere.py

      - name: Run SE3_examples
        run: |
          python3 mrobpy/tests/SE3_examples.py

      - name: Run FGraph_landmark_3d_example
        run: |
          python3 mrobpy/tests/FGraph_landmark_3d_example.py

      - name: Run FGraph_landmark_2d_example
        run: |
          python3 mrobpy/tests/FGraph_landmark_2d_example.py

      - name: Run PC_align
        run: |
          python3 mrobpy/tests/PC_align.py

